"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from decouple import config
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6)*s9)()y&g&yt%@p#)t^q+j+1u843)&-w-zu*s$0k50q03k92'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cities_light',
    'widget_tweaks',
    'django_countries',
    'whitenoise.runserver_nostatic',
    'crispy_forms',
    'crispy_bootstrap5',
    'captcha',
    'django_crontab',
    "django_apscheduler",
    
     # Authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Providers (for social logins)
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'main.apps.MainConfig',
    
    
]

CRONJOBS = [
    ('0 3 * * *', 'main.cron.update_career_feeds'),  
]


SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = 'chef_dashboard'  # or wherever you want users to land
LOGOUT_REDIRECT_URL = 'home'

SOCIALACCOUNT_ADAPTER = "main.adapters.CustomSocialAccountAdapter"
SOCIALACCOUNT_LOGIN_ON_GET = True

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = "none"  
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]






SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '206006494015-0nvufrfrgabhveo8d1svujiihq53v0tg.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

RECAPTCHA_PUBLIC_KEY = '6LdhLfIrAAAAAHGCC_vt8byz7lEwtCZbDRJTCGp7'
RECAPTCHA_PRIVATE_KEY = '6LdhLfIrAAAAAPpe7F-7hbQXH05KrGjomufwnDs_'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']



# PAYSTACK
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')

FLW_SECRET_KEY = os.getenv('FLW_SECRET_KEY')
FLW_PUBLIC_KEY = os.getenv('FLW_PUBLIC_KEY')


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
    
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # global templates folder (optional)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# ========================
# EMAIL SETTINGS
# ========================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False         # ❌ Disable TLS
EMAIL_USE_SSL = True          # ✅ Enable SSL
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "atechincc@gmail.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "your_app_password_here")
DEFAULT_FROM_EMAIL = "ChefHub <atechincc@gmail.com>"


ADMINS = [
    ('Site Admin', 'atechincc@gmail.com'),
]

OPENAI_API_KEY = config('OPENAI_API_KEY')
# DEFAULT_FROM_EMAIL = 'no-reply@chefscom.com'

HF_API_TOKEN = os.getenv("HF_API_TOKEN")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CITIES_LIGHT_DATA_DIR = os.path.join(BASE_DIR, 'cities_light_data')
DATA_DIR = CITIES_LIGHT_DATA_DIR


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'chef_dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_REDIRECT_URL = '/redirect-after-login/'

