# Generated by Django 5.2.7 on 2025-11-04 11:38

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
        migrations.AlterField(
            model_name='chefprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
