# Generated by Django 5.2.7 on 2025-11-05 18:06

import main.models
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chefprofile_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
        migrations.AlterField(
            model_name='needchefsubmission',
            name='meals_accommodation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('yes', 'Yes'), ('no', 'No'), ('partly', 'Partly')], default='no', max_length=20),
        ),
    ]
