# Generated by Django 5.2.7 on 2025-11-25 16:50

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_jobvacancysubmission_status_alter_candidate_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.jobvacancysubmission'),
        ),
    ]
