# Generated by Django 5.2.7 on 2025-11-25 21:08

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_candidate_cv_alter_jobapplication_job_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonylog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobapplication'),
        ),
        migrations.AddField(
            model_name='testimonylog',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
    ]
