# Generated by Django 5.2.7 on 2025-11-26 15:06

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_candidate_cv_alter_jobengagement_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
        migrations.AlterField(
            model_name='jobengagement',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_engagements_as_candidate', to=settings.AUTH_USER_MODEL),
        ),
    ]
