# Generated by Django 5.2.7 on 2025-11-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_candidate_cv_alter_jobengagement_candidate'),
    ]

    operations = [
    ]
