# Generated by Django 5.2.7 on 2025-11-27 11:16

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_cvsubmission_cv_submission_alter_candidate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobengagement',
            name='cv_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cvsubmission'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
    ]
