# Generated by Django 5.2.7 on 2025-11-27 11:24

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_jobengagement_cv_submission_alter_candidate_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvsubmission',
            name='cv_submission',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
    ]
