# Generated by Django 5.2.7 on 2025-11-27 11:51

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_cvsubmission_cv_submission_alter_candidate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobengagement',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobengagement',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
    ]
