# Generated by Django 5.2.7 on 2025-11-27 12:01

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_jobengagement_country_jobengagement_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobengagement',
            old_name='country',
            new_name='candidate_country',
        ),
        migrations.RenameField(
            model_name='jobengagement',
            old_name='phone',
            new_name='candidate_phone',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
    ]
