# Generated by Django 5.2.7 on 2025-11-28 08:06

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_country_jobengagement_candidate_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('published', models.DateTimeField()),
                ('source', models.CharField(default='Escoffier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
    ]
