# Generated by Django 5.2.7 on 2025-11-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20251126_1802'),
        ('main', '0020_alter_candidate_cv_alter_jobengagement_application'),
        ('main', '0025_careeradvice_alter_candidate_cv'),
    ]

    operations = [
    ]
