# Generated by Django 5.2.7 on 2025-12-04 11:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_candidate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_viewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=main.models.cv_upload_to),
        ),
    ]
